# Generated by Django 3.1.2 on 2021-01-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.TextField(),
        ),
    ]
