# Generated by Django 3.1.2 on 2021-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210104_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.TextField(),
        ),
    ]
