# Generated by Django 3.1.2 on 2021-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210120_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='name',
        ),
        migrations.AlterField(
            model_name='landmark',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
