# Generated by Django 3.1.2 on 2021-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
