# Generated by Django 3.1.2 on 2021-02-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210120_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='markertype',
            field=models.TextField(default='1'),
        ),
    ]
