# Generated by Django 3.1.2 on 2021-02-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210203_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('landmark', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.landmark')),
            ],
        ),
    ]
