# Generated by Django 3.1.2 on 2021-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210214_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
