# Generated by Django 3.1.2 on 2021-02-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_landmarkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmarkimage',
            name='images',
        ),
        migrations.AddField(
            model_name='landmarkimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='landmarkimage',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='landmark', to='api.landmark'),
        ),
    ]
