# Generated by Django 3.1.2 on 2021-02-17 19:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210217_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='centre_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='centre_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='zoom_level',
            new_name='zoom',
        ),
        migrations.AlterField(
            model_name='map',
            name='style',
            field=models.ForeignKey(default=1, on_delete=models.SET(api.models.get_default_style), related_name='maps', to='api.mapstyle'),
            preserve_default=False,
        ),
    ]
