# Generated by Django 3.1.2 on 2021-02-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_landmark_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='landmark',
            name='layer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='layer', to='api.layer'),
        ),
    ]
