# Generated by Django 3.1.2 on 2021-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210217_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='zoom',
            field=models.FloatField(),
        ),
    ]
