# Generated by Django 3.1.2 on 2021-02-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210217_1947'),
        ('api', '0013_auto_20210216_1137'),
    ]

    operations = [
    ]
