# Generated by Django 3.1.2 on 2021-02-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0016_merge_20210217_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
