# Generated by Django 3.1.2 on 2021-02-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210217_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='layer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='layer', to='api.layer'),
        ),
    ]
