# Generated by Django 3.1.2 on 2021-02-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210223_1705'),
        ('api', '0024_auto_20210217_1748'),
    ]

    operations = [
    ]
