# Generated by Django 3.1.2 on 2021-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210310_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkimage',
            name='image_name',
            field=models.CharField(max_length=64),
        ),
    ]
