# Generated by Django 3.1.2 on 2021-03-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210311_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
    ]
