# Generated by Django 3.1.2 on 2021-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210310_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkimage',
            name='image_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
