# Generated by Django 3.1.2 on 2021-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_layer_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarkimage',
            name='image',
            field=models.ImageField(default=None, max_length=1000, upload_to='images/'),
        ),
    ]
