# Generated by Django 3.1.2 on 2021-03-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210310_1717'),
        ('api', '0026_auto_20210310_1051'),
    ]

    operations = [
    ]
