# Generated by Django 3.1.2 on 2021-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210310_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='type',
            field=models.TextField(choices=[('DIR', 'Directional'), ('FIL', 'Fill'), ('NDR', 'Non-directional')], default='NDR'),
        ),
    ]
