# Generated by Django 3.1.2 on 2021-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_layer_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='colour',
            field=models.TextField(default='#000000'),
        ),
    ]
