# Generated by Django 3.1.2 on 2021-03-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210318_2112'),
        ('api', '0031_auto_20210324_1305'),
    ]

    operations = [
    ]
