# Generated by Django 3.1.2 on 2021-03-24 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0032_merge_20210324_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': (django.db.models.functions.text.Lower('title'),)},
        ),
        migrations.AlterField(
            model_name='landmarkimage',
            name='image_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
