# Generated by Django 3.1.2 on 2021-03-26 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0033_auto_20210324_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hash_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='projects', to='auth.group'),
        ),
    ]
