# Generated by Django 3.1.6 on 2021-03-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20210324_1128'),
        ('api', '0033_auto_20210324_1846'),
    ]

    operations = [
    ]
