# Generated by Django 3.1.2 on 2021-03-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210326_1710'),
        ('api', '0034_auto_20210326_1506'),
    ]

    operations = [
    ]
