# Generated by Django 3.1.2 on 2021-03-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210326_1925'),
        ('api', '0035_auto_20210326_1701'),
    ]

    operations = [
    ]
