image: python:3.8.6-buster
build:
  tags:
    - docker
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r backend/requirements.txt
    - python backend/manage.py migrate
    - python backend/manage.py test